---@meta ParserDefs

---A Parser object returned by addons
---@class Parser: ParserAPI
---@field priority number
---@field api_version string    The minimum API version the string requires.
---@field version string        The minimum API version the string requires. @deprecated.
---
---@field can_parse fun(self: Parser, directory: string, parse_state: ParseState): boolean
---@field parse fun(self: Parser, directory: string, parse_state: ParseState)
---@field setup fun(self: Parser)?
---
---@field name string
---@field keybind_name string?
---@field keybinds Keybind[]?

---The Parse State object passed to the can_parse and parse methods
---@class ParseState: ParseStateAPI
---@field source 'browser'|'loadlist'|'script-message'|'addon'|string
---@field directory string
---@field already_deferred boolean?
---@field yield fun(self: ParseState, ...:unknown): ...